### ISSUE TITLE
Cannot find module 'use-latest-callback' 

### ISSUE THREAD

**Issue by KelvinPortuphy** [satya164/use-latest-callback#6]
Cannot find module 'use-latest-callback' or its corresponding type declarations.ts(2307)

this is happening version 0.1.8

**Comment by sivakusayan** [comment]
I'm getting this error from `@react-navigation/core`. Likely because its `package.json` [always uses the latest minor version of this library](https://github.com/react-navigation/react-navigation/blob/main/packages/core/package.json#L43) and something changed with the latest release, if I'm understanding correctly.

**Comment by unstableair** [comment]
I'm also getting module resolve issues at v 0.1.8  The package seems to work ok if I regress to 0.1.7

` Error: While trying to resolve module use-latest-callback from file .../node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx, the package .../node_modules/use-latest-callback/package.json was successfully found. However, this package itself specifies a main module field that could not be resolved `

**Comment by sivakusayan** [comment]
Yeah, the bandaid fix I'm going to go with for now is to use [yarn dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force this package's version to be 0.1.7. There is probably an analogous feature people can use in other package managers.

**Edit:** Or not. Seems this was fixed in 0.1.9.

**Comment by Epothos333** [comment]
I had the same error. That it could not find `/node_modules/use-latest-callback/lib/index.js`.

As a temp fix, I looked through my `node_modules` and found that `index.js` was actually in `.../lib/src/index.js`. So I copied all the files from `src` to `lib` and patched the package.

The exact error:


error: Error: While trying to resolve module `use-latest-callback` from file `/Users/Me/Documents/PS/mobile/node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx`, the package `/Users/Me/Documents/PS/mobile/node_modules/use-latest-callback/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/Me/Documents/PS/mobile/node_modules/use-latest-callback/lib/index.js`. Indeed, none of these files exist:

  * /Users/Me/Documents/PS/mobile/node_modules/use-latest-callback/lib/index.js(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)


The new file layout
![image](https://github.com/satya164/use-latest-callback/assets/9576668/a6dd8c03-642b-42d6-8cbb-0ced5e16a53d)

**Comment by JDWaghela** [comment]
Cleared node_modules 5 times yet its picking version 0.1.7

**Comment by JDWaghela** [comment]
> Cleared node_modules 5 times yet its picking version 0.1.7

Resolved now

**Comment by KelvinPortuphy** [comment]
Closing this issue
